# Generated by Django 3.1.7 on 2021-04-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_studio_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiosession',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
