# Generated by Django 3.1.7 on 2021-04-16 14:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studio', '0004_auto_20210416_1709'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudSession',
            new_name='StudioSession',
        ),
    ]
