# Generated by Django 3.1.7 on 2021-04-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_auto_20210416_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiosession',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
