# Generated by Django 3.1.7 on 2021-04-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_auto_20210416_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studiosession',
            name='available',
        ),
        migrations.AddField(
            model_name='studiosession',
            name='count_hours',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='studiosession',
            name='time',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
