# Generated by Django 3.1.7 on 2021-04-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_auto_20210420_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='opening_days_hours',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
