# Generated by Django 3.1.7 on 2021-04-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_soundengineer_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiosession',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
