# Generated by Django 3.1.7 on 2021-04-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0011_studiosession_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiosession',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
